home/controleambiente/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import views

app_name = 'controleambiente'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    
]

home/home/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('controleambiente.urls')),

]

home/controleambiente/models.py
from django.db import models
from django.utils import timezone

    
class Local(models.Model):
    nome = models.CharField(max_length = 100, unique=True)
    status = models.CharField(max_length = 100, blank=True, default="OK")

    def __str__(self):
        return self.nome

class Ambiente(models.Model):
    temperatura = models.DecimalField(max_digits=8, decimal_places=5)
    umidade = models.DecimalField(max_digits=8, decimal_places=5)
    data = models.DateTimeField(default=timezone.now)
    local = models.ForeignKey('Local', max_length = 100, on_delete=models.CASCADE, blank=False, default=1)

    def __str__(self):
        return str(self.local.nome) + " - " + str(self.data)

class ArcondState(models.Model):
    onoff = models.IntegerField(blank=True, null=True)
    local = models.ForeignKey('Local', max_length = 100, on_delete=models.CASCADE, blank=False, default=1)
    data = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return str(self.local.nome) + " - " + str(self.onoff) + " - " + str(self.data)

home/controleambiente/views.py
from django.http import HttpResponse
import datetime
from django.shortcuts import render
from django.template import Template, Context
import math
from random import *
from controleambiente.models import Local, Ambiente, ArcondState
import json
from django.core import serializers


def teste(request):
    now = str(datetime.datetime.now()) + "  " + "Otavio"
    return HttpResponse(now)

def homenew(request):
    now = str(datetime.datetime.now()) + "  " + "Otavio"
    return HttpResponse(now)

def leArquivo(sensor):
    file = open('/home/pi/Projetos/'+sensor, 'r')
    valorLido = file.read()
    indice = (valorLido).index(';')
    temperatura = valorLido[0:indice]
    umidade = valorLido[indice+1:]
    return (temperatura, umidade)


def home(request):
    variavel =  "variavel passada"
    #arquivo = (leArquivo("sensor_23"))
    temp1 = 11.1
    umid1 = 22.2
    #arquivo = (leArquivo("sensor_24"))
    temp2 = 50.0#arquivo[0]
    umid2 = 17.7#arquivo[1]
    locals = []
    locals = json.dumps(serializers.serialize('json', Local.objects.all()))

    ambiente = []
    


    #novo Local
    room = Local.objects.all()
   
    try:
        ambiente = json.dumps(serializers.serialize('json', Ambiente.objects.order_by('-id')[:100]))
    except Exception as ex:
        ambiente = 'deupau20' + str(ex)

    #arcond = json.dumps(serializers.serialize('json', ArcondState.objects.all().last()))
    arcond1 = ArcondState.objects.filter(local = 0).last()
    arcond2 = ArcondState.objects.filter(local = 1).last()
    return render(request, 'controleambiente/pessoal.html', {'temp1': temp1, 'umid1': umid1, 'temp2': temp2, 'umid2': umid2, 'ambiente': ambiente, 'arcond1': arcond1, 'arcond2': arcond2, 'room': room})


#def home(request):
    #return render(request, 'controleambiente/pessoal.html',)

home/controleambiente/templates/controleambiente/pessoal.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<link rel="apple-touch-icon" sizes="57x57" href="{% static "img/favicon/apple-icon-57x57.png" %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static "img/favicon/android-icon-192x192.png" %}">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
<link href="{% static "css/weather-icons.min.css" %}" rel="stylesheet" media="screen">
<link type="text/css" href="{% static "css/style.css" %}" rel="stylesheet" media="screen">
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script>var ambiente = JSON.parse({{ambiente|safe}})</script>
<script src="{% static 'js/plot.js' %}"></script>
<title>AutoHome</title>
</head>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <!-- Logo -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'controleambiente:home' %}">AutoHome</a>
        </div>
        <!-- last update -->
        <div class="text-light" id="horaagora">    
            <p> ultima atualizacao </p>
            {{ sen1 }}
        </div>		 
    </div>
</nav>

<body>
    





<div class="quadro" style="border-radius: 4px;background:cyan;height:100px;width:80%;margin:0 auto;margin-top:40px;">

    <div class="qesq" style="border-radius: 4px;background:#537686;float:left;height:100px;width:100%;">
        
        <!--foto-->
        <div class="foto" style="float:left;height:100px;width:25%;">
            <div style="margin-top:20px;height:100px;width:100%;text-align:center-vertical;"><img src="{% static "img/zep.png" %}" class="rounded-circle" alt="zep" height="60px" style="margin:auto;display:block" /></div>
        </div>
        
        <!-- informacoes -->
        <div class="info" style="float:left;height:50px;width:15%;float:left;position:relative">
            <div style="margin-top:10px;margin-right:10px;text-align:right"><i class="wi wi-thermometer"></i> </div>
        </div>
        <div class="info" style="float:left;height:50px;width:60%;float:left;position:relative;">
            <div id="tempm" style="margin-top:10px">˚C </div>  
        </div>
        <div class="info" style="float:left;height:50px;width:15%;float:left;position:relative">
            <div style="margin-top:10px;margin-right:10px;text-align:right"><i class="wi wi-humidity"></i></div>
        </div>
        <div class="info" style="float:left;height:50px;width:60%;float:left;position:relative;">
            <div style="margin-top:10px">{{umid1}}% </div>  
        </div>
        <!--
        <div class="info" style="float:left;height:100px;width:100%;float:left;position:relative;">
            <div id="myDiv" style="margin:0 auto;height:100px;width:80%;"></div>
        </div>
        -->
    </div>
    
        

</div>

<div class="quadro" style="border-radius: 4px;background:pink;height:100px;width:80%;margin:0 auto;margin-top:40px;">

    <div class="qesq" style="border-radius: 4px;background:pink;float:left;height:100px;width:100%;">
        
        <!--foto-->
        <div class="foto" style="float:left;height:100px;width:25%;">
            <div style="margin-top:20px;height:100px;width:100%;text-align:center-vertical;"><img src="{% static "img/tete.png" %}" class="rounded-circle" alt="zep" height="60px" style="margin:auto;display:block" /></div>
        </div>
        <!-- informacoes -->
        <div class="info2" style="float:left;height:50px;width:15%;float:left;position:relative">
            <div style="margin-top:10px;margin-right:10px;text-align:right"><i class="wi wi-thermometer"></i> </div>
        </div>
        <div class="info2" style="float:left;height:50px;width:60%;float:left;position:relative;">
            <div id="tempn" style="margin-top:10px">˚C </div>  
        </div>
        <div class="info2" style="float:left;height:50px;width:15%;float:left;position:relative">
            <div style="margin-top:10px;margin-right:10px;text-align:right"><i class="wi wi-humidity"></i></div>
        </div>
        <div class="info2" style="float:left;height:50px;width:60%;float:left;position:relative;">
            <div style="margin-top:10px">{{umid1}}% </div>  
        </div>
        
    </div>
        
</div>
<br>
<div id="myDiv" style="background-color:rgb(150,150,150);border-radius: 4px;margin:0 auto;height:200px;width:80%;"></div>
<br>


<!--<div id="line_top_x" ></div>-->
<div class="container" style="color: white";>

 {{ arcond1.local }}
 {{ arcond1.onoff }}
 <br>
 {{ arcond2.local }}
 {{ arcond2.onoff }}

</div>

<div style="color: cyan;">
{% for i in room %}
    <p>{{ i.nome }}</p>
{% endfor %}
</div>


</body>
</html> 